### ISSUE TITLE
new version available (2.6.4) and mandatory(?)

### ISSUE THREAD

**Issue by rpicot-lecko** [Sidicer/nordlayer#6]
Hello there,
Just a quick message to say that a new version is available, and it seems the current version is not enough to connect.

I tried to just up the version numbers and update the checksum (taking the last version upgrade as a model on the commit history), the install completed but I still can't connect.
Not sure If I missed an obvious step or if there more to do.

**Comment by rpicot-lecko** [comment]
of course just 10 minutes after the message I find the solution.
Doing just a `makepkg -si` wont work if it's already installed.

For those who can't wait for a proper fix :
sudo nordlayer logout 
yay -R nordlayer
git clone https://github.com/Sidicer/nordlayer.git
cd nordlayer

in PKGBUILD and .SRCINFO
replace the version number by `2.6.4`
and the sha256sums by `2f11fd0fd98f9a627fbcde60832f8dbf5d5478bc9bf93b71ca99d26dd89b46e28ae080bcbe0db2a6e3c7ca097e77d753d6627ffdae318aedcf716566d15b30dc`

then
makepkg -si

This should be enough

(and my apologies to [Sidicer](https://github.com/Sidicer), I don't have time to learn how to make a proper pull request right now)

**Comment by Sidicer** [comment]
Thank you @rpicot-lecko. This was helpful. 
Can confirm currently, that just upgrading nordlayer directly breaks it. A full reinstall is required for `2.6.3` -> `2.6.4` upgrade. Will see how to implement that

**Comment by Sidicer** [comment]
A full reinstall is not required.
```sh
rm /var/lib/nordlayer/nordlayer.db
systemctl restart nordlayer
nordlayer login
```
